### ISSUE TITLE
SASS website sketches 

### ISSUE THREAD

**Issue by NikCasar** [NikCasar/saas-website#1]
![SASS-sketch-1](https://user-images.githubusercontent.com/55094132/78934624-44ac5e80-7a79-11ea-9bac-227041896e32.jpg)
![SASS-sketch-2](https://user-images.githubusercontent.com/55094132/78934638-483fe580-7a79-11ea-9998-1b9cf5f96c14.jpg)
 nikki 

@muxlowc

**Comment by muxlowc** [comment]
@NikCasar these look fine, but can you please mark them up showing some html tags (ie. header, footer, any grids/units/tables/form, sections etc)?

**Comment by NikCasar** [comment]
![sketch3](https://user-images.githubusercontent.com/55094132/79049951-c5439a00-7bf4-11ea-85bc-d7780f3f6c94.jpg)
![sketch4](https://user-images.githubusercontent.com/55094132/79049952-ca084e00-7bf4-11ea-98a0-21bf669d1326.jpg)


I just put the html tags on it quickly, hopefully that's ok. -nikki casar 

@muxlowc

**Comment by muxlowc** [comment]
@NikCasar thanks!
